message:
  no_auth: §4您没有权限执行该指令
  command_error: §4指令解析出错：
  not_player: §4该指令只能被玩家执行
  grammar_error: §4语法错误，使用 sw help 获取帮助
  unknown_item: §4不存在的道具
  config_error: §4无法解析配置，请检查配置文件
  config_cannot_resolve: §4无法解析配置：{}
  unknown_player: §4玩家不存在
  unknown_attribute: §4不存在的属性
  cannot_operate: §4无法完成操作
  line_number: 行号
  reloaded: §a配置文件已重新读取
  promote_change:  §b强化成功！§a属性[%s.%s]发生变化:[%s]
  promote_reset:  §b强化成功！§a属性[%s.%s]重写为:[%s]
  promote_fail: §4强化失败！
  check_not_pass: §4强化失败，未发生改变！
  got_sea_gift: §b获得了海之馈赠：%s！
  help_msg: |
    §c§l--- §aSW 帮助信息 §c§l---
    §a§l/sw refine [<玩家>] §e打开洗炼菜单
    §a§l/sw strengthen [<玩家>] §e打开强化菜单
    §a§l/sw help §e显示本帮助信息
  admin_help_msg: |
    §c§l--- §aSW 管理指令 §c§l---
    §b§l/sw give <玩家> <道具名> <数量> §e给予指定玩家道具
    §b§l/sw enchant <附魔ID> <附魔等级> §e对主手上的物品进行附魔
    §b§l/sw lore set <行号> <Lore内容> §e修改主手上物品的 Lore
    §b§l/sw lore del <行号> §e删除主手上物品指定行的 Lore
    §b§l/sw promote <原料名> §e使用指定的原料对主手上的物品进行强化
    §b§l/sw rename <新名称> §e重命名道具

# 自定义附魔
enchants:
  # 注释掉整个配置即可禁用一个附魔
  # 用在弓上时，每提升一级可以额外射出 addition 支箭
  ARROW_RAIN:
    key: ARROW_RAIN
    displayName: §b箭雨
    addition: 1
  # 拥有此附魔的鱼竿有概率钓到配置的道具
  GIFT_OF_THE_SEA:
    key: GIFT_OF_THE_SEA
    displayName: §6海之馈赠
    addition: 10
  # 近战攻击时有概率吸血
  SUCK_BLOOD:
    key: SUCK_BLOOD
    displayName: §6嗜血
    addition: 20

# 只有 FURNACE、ANVIL 支持性较好，基岩版兼容性更差，需要考虑燃料等情况
# 比如，使用 FURNACE 时，必须将原料配置为燃料类，否则基岩版玩家无法使用 GUI，Java 版无需关心
refineType: FURNACE
refineTitle: §6§l洗炼炉
strengthType: FURNACE
strengthTitle: §c§l精炼台
# 关闭后，玩家将不能对插件道具进行附魔、祛魔、改名等
enablePlayerEnchant: false
# 启用自定义附魔修复，如果因为 ProtocolSupport 等插件导致自定义附魔丢失可以开启此配置项
usingLoreGetter: true