name: StrengthenWeapon
main: fun.nekomc.sw.StrengthenWeapon
version: '1.0-beta.2'
api-version: '1.18'
author: ourange

commands:
  sw:
    description: Strengthen plugin for NekoMC.
    usage: ยง4Wrong usage, type ยงb/<command> help ยง4for help.
