name: StrengthenWeapon
main: fun.nekomc.sw.StrengthenWeapon
version: '1.0-beta.4'
api-version: '1.18'
authors: [ChiruMori, ourange]
website: https://github.com/nekoMC/StrengthenWeapon
description: 支持高度定制化配置的道具强化插件

commands:
  sw:
    description: Strengthen plugin for NekoMC.
    usage: §4Wrong usage, type §b/<command> help §4for help.
