name: StrengthenWeapon
main: com.ourange.strengthen_weapon.StrengthenWeapon
version: '0.1'
api-version: '1.18'
author: ourange

commands:
  sw:
    description: My INventory Test Command
    usage: /<command>
