sw_bow:
  displayName: sw_bow
  name: §b[强化弓]
  levelName: §b等级:+
  level: 1
  lore:
    - §aline 1
    - §bline 2
  material: BOW
sw_stone:
  displayName: sw_stone
  name: §b[强化石]
  levelName: '§b等级:'
  level: 0
  lore:
    - §aline 1
    - §bline 2
  material: RAW_COPPER
  chance:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    - 90
    - 99